import { FILTER_DEFAULTS, type IntelligenceReport, type IntelligenceRow } from './intelligenceApi';
export const person = (i = 1): IntelligenceRow => ({
  owner_key: String(i),
  display_name: `Rahimov Ali-${i}`,
  department: 'Terapiya',
  job_title: 'O‘qituvchi',
  role: 'hodim',
  last_login: null,
  minutes: 35,
  active_days: 2,
  pages: [],
  videos_viewed: 0,
  handouts_viewed: 1,
  cases_created: 1,
  tests_created: 1,
  handouts_created: 0,
  videos_created: 0,
  presentations_created: 0,
  live_sessions: 1,
  online_lessons: 0,
  students_taught: 10,
  student_attempts: 10,
  avg_student_score: 70,
  created_total: 2,
  lessons_total: 1,
  is_active: true,
  signals: [],
  attention_count: 0,
  small_sample: false,
  previous: null,
  delta: { minutes: 5, created_total: 1, lessons_total: 1, student_attempts: 10 },
});
export const reportFixture: IntelligenceReport = {
  from: '2026-09-01',
  to: '2026-09-14',
  previous_from: '2026-08-18',
  previous_to: '2026-08-31',
  generated_at: '2026-09-14T12:00:00Z',
  total: 2,
  count: 2,
  rows: [person(1), person(2)],
  summary: {
    teachers: 2,
    active: 2,
    minutes: 70,
    materials: 4,
    lessons: 2,
    attempts: 20,
    signals: {},
  },
  filters: { ...FILTER_DEFAULTS, date_from: '2026-09-01', date_to: '2026-09-14', department: '' },
  signal_labels: { no_lessons: 'Dars yo‘q', no_activity: 'Faollik yo‘q' },
};
